### ISSUE TITLE
Migrar Cuaderno de bitácora

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/asroboturret#2]
Migrar el cuaderno de bitácora de RoboFactory (la parte de asroboturret) a la wiki de este repo, como en [ASROB-CADE](https://github.com/asrob-uc3m/ASROB-CADE/wiki/Cuaderno-de-Bit%C3%A1cora) y [AIr-hockey](https://github.com/asrob-uc3m/air-hockey/wiki/Cuaderno-de-Bit%C3%A1cora).

**Comment by davidvelascogarcia** [comment]
@David-Estevez  Listo, el cuaderno de bitácora ya se ha migrado, pero me faltan los datos para rellenarlo del todo.

**Comment by David-Estevez** [comment]
¿Qué datos necesitas?

**Comment by davidvelascogarcia** [comment]
Me refería a las sesiones previas que no están en el cuaderno de bitácora de github. ¿Están en la web de Asrob?

**Comment by David-Estevez** [comment]
En principio el resto del cuaderno está [aquí](http://asrob.uc3m.es/index.php/RoboFactory:_Cuaderno_de_Bit%C3%A1cora), pero no veo nada sobre torretas.

Quizá @JuanFdelArco nos pueda echar una mano para saber si hay algo más que incluir o se puede cerrar ya la issue.

**Comment by davidvelascogarcia** [comment]
He pasado toda la documentación del cuaderno al nuevo. He rellenado con algunos datos que sabía, para el resto espero a ver si @JuanFdelArco  o @carlosmgomezj , pudieran ayudar.

**Comment by davidvelascogarcia** [comment]
@David-Estevez , en esta issue, ¿hace falta algo más?, o ¿se puede cerrar?.

**Comment by David-Estevez** [comment]
Si has hablado con ellos y no hay nada más que rellenar se puede cerrar.

**Comment by David-Estevez** [comment]
@davidvelascogarcia si no la cierras tú la cierro yo 😜

**Comment by davidvelascogarcia** [comment]
@David-Estevez  jajaja no te preocupes, ya me encargo. Se me había pasado ;)

**Comment by David-Estevez** [comment]
Me lo había imaginado jajajaja
